project_id: '436128'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
  # JSON translation files
  {
    source: '/website/i18n/en/**/*',
    translation: '/website/i18n/%two_letters_code%/**/%original_file_name%',
  },
  # Docs Markdown files
  {
    source: '/website/docs/**/*',
    translation: '/website/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
  },
  # Blog Markdown files
  {
    source: '/website/blog/**/*',
    translation: '/website/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%',
  },
]
